### ISSUE TITLE
Latest update doesn't install on whyred

### ISSUE THREAD

**Issue by IdanHo** [Magisk-Modules-Repo/CAIO#2]
When trying to flash it says your device isnt supported with empty brackets, screenshot included 
![Screenshot_2019-05-28-23-06-34-815_com K LkVbou v Uo YY](https://user-images.githubusercontent.com/16208640/58508739-6d976e00-819d-11e9-8464-1859bb7a2627.png)

**Comment by J0hnTR** [comment]
Got here to add this Issue! Same for me!

Here is archive that was downloaded during install: [https://drive.google.com/file/d/1FBWr18LImvQM5Vx6_IJywHJ6JZBp69Ip/view?usp=sharing](https://drive.google.com/file/d/1FBWr18LImvQM5Vx6_IJywHJ6JZBp69Ip/view?usp=sharing)
Here is an install log: [magisk_install_log_2019-06-154T10:48:34Z.log](https://github.com/Magisk-Modules-Repo/CAIO/files/3246429/magisk_install_log_2019-06-154T10.48.34Z.log)

Some additional screenshots:
![Screenshot_2019-06-03-10-50-21-424_com topjohnwu magisk](https://user-images.githubusercontent.com/1292549/58785234-d17ec400-85ed-11e9-99f6-c8490647c609.png)
![Screenshot_2019-06-03-10-47-42-224_com android settings](https://user-images.githubusercontent.com/1292549/58785235-d17ec400-85ed-11e9-9c0e-e20ba6b138f8.png)

**Comment by J0hnTR** [comment]
Adding CAIO-debug.log: [https://drive.google.com/file/d/15rCTz_pPNRqBHpG7QGohVmEGfEg2D2JO/view?usp=sharing](https://drive.google.com/file/d/15rCTz_pPNRqBHpG7QGohVmEGfEg2D2JO/view?usp=sharing)

**Comment by J0hnTR** [comment]
Hello, anyone here?..

**Comment by J0hnTR** [comment]
Still error on latest version.

- Copying zip to temp directory
- Installing [SDM660]_Camera_All-in-One-Slap_n_Bless.zip
Archive:  /data/user/0/com.mJ.CnBIP.pVtiq.k/cache/install.zip
  inflating: sepolicy.sh
  inflating: system.prop
  inflating: unity_install.sh
  inflating: unity_uninstall.sh
  inflating: unity_upgrade.sh
  inflating: addon.sh
  inflating: busybox
  inflating: busybox
  inflating: util_functions.sh
  inflating: install.sh
  inflating: module.prop
  inflating: uninstall.sh
 
Unzipping files...
 
    *******************************************
    *       [SDM660] Camera All-in-One        *
    *******************************************
    *              Slap n Bless               *
    * by atiprusma, Hadinata & ANCIENT Family *
    *******************************************
 
- MagiskSU detected
  !  is not supported
! Installation failed

**Comment by J0hnTR** [comment]
Still nothing on Wa Ratusz - error is the same.

**Comment by atiprusma** [comment]
> Still nothing on Wa Ratusz - error is the same.

Sorry i didn't browse github since then, 
by looking to your attached debug log, i found it weird because your device couldn't get recognized by this module.
have you tried to install from recovery?

**Comment by J0hnTR** [comment]
Yes, with the same error..(

**Comment by IdanHo** [comment]
It actually installed fine for me. No idea what changed.

**Comment by atiprusma** [comment]
> Yes, with the same error..(

this module reads vendor props to recognize device, which what i saw from your log it read nothing.
maybe because oreo limitation or there's some other module/app causing this.

**Comment by atiprusma** [comment]
> It actually installed fine for me. No idea what changed.

latest one?

**Comment by J0hnTR** [comment]
My build.prop: https://drive.google.com/file/d/1-63so9cJcnWIeJpruvuI3k0AGYWhsqPT/view?usp=drivesdk

**Comment by IdanHo** [comment]
> > It actually installed fine for me. No idea what changed.
> 
> latest one?

Yep, but im on pie

**Comment by atiprusma** [comment]
> My build.prop: https://drive.google.com/file/d/1-63so9cJcnWIeJpruvuI3k0AGYWhsqPT/view?usp=drivesdk

i meant build.prop from vendor, not system prop.

**Comment by atiprusma** [comment]
> > > It actually installed fine for me. No idea what changed.
> > 
> > 
> > latest one?
> 
> Yep, but im on pie

good to know

**Comment by J0hnTR** [comment]
Oooops.
Checked install.sh, now I see.

It looks for:
ro.product.vendor.model
ro.product.vendor.device

But I have in /vendor/build.prop:
ro.vendor.product.model=Redmi Note 5
ro.vendor.product.device=whyred

LOL

**Comment by IdanHo** [comment]
Yep in pie its the way the script expects. Should probably just add a check if either is right

**Comment by atiprusma** [comment]
[Solved]
Definitely memeui oreo limitation.

**Comment by J0hnTR** [comment]
Just for record.
Added lines needed in /vendor/build.prop - like this:
ro.vendor.product.model=Redmi Note 5
ro.product.vendor.model=Redmi Note 5
ro.vendor.product.device=whyred
ro.product.vendor.device=whyred
Installed and worked like a charm.
