### ISSUE TITLE
Device adding request

### ISSUE THREAD

**Issue by Imranislamemu** [Magisk-Modules-Repo/CAIO#3]
Hello Dear!

A humble request to you. My device is MI Note 3 running on sd660. I'm adding the system info for your information. I want to use this module eagerly. But this is not flashing now a days. Could you please add my device support also?

Seeing my device in your list will be appreciated!

Note: previously i could install your module but after may update I'm unable to install.  

![Screenshot_2019-08-08-04-23-40-218_com android settings](https://user-images.githubusercontent.com/53881144/62662210-2267bb80-b995-11e9-892a-60c9a90a6c2d.png)

**Comment by atiprusma** [comment]
I'll do it later, maybe.
